language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
 - composer --prefer-dist install

before_script:
 - mkdir -p build/coverage

script:
 - phpunit

after_script:
 - vendor/bin/coveralls -v --exclude-no-stmt