language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  
install:
 - composer --prefer-dist install

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 src/ tests/
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ] || [ "$TRAVIS_PHP_VERSION" == "5.4" ] || [ "$TRAVIS_PHP_VERSION" == "5.5" ]; then ./vendor/bin/paratest -f --phpunit ./vendor/bin/phpunit --coverage-clover=coverage.clover; else ./vendor/bin/phpunit -v --debug --coverage-clover=coverage.clover; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
